diameter_client:
  peer: 10.90.250.32
  port: 3868
  OriginHost: shbridge.ims.mnc435.mcc311.3gppnetwork.org
  OriginRealm: ims.mnc435.mcc311.3gppnetwork.org
  DestinationHost: hss01.epc.mnc435.mcc311.3gppnetwork.org
  DestinationRealm: epc.mnc435.mcc311.3gppnetwork.org



freeswitch_esl:
  username: 'ClueCon'         # default ESL user
  password: 'ClueCon'         # default ESL pass
  host: '127.0.0.1'
  port: 8021
